// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMedia() {
  return window['go']['main']['App']['GetMedia']();
}

export function GetShortcuts() {
  return window['go']['main']['App']['GetShortcuts']();
}

export function Next() {
  return window['go']['main']['App']['Next']();
}

export function OpenFocusSettings() {
  return window['go']['main']['App']['OpenFocusSettings']();
}

export function OpenNotifications() {
  return window['go']['main']['App']['OpenNotifications']();
}

export function OpenShortcut(arg1) {
  return window['go']['main']['App']['OpenShortcut'](arg1);
}

export function PlayPause() {
  return window['go']['main']['App']['PlayPause']();
}

export function Previous() {
  return window['go']['main']['App']['Previous']();
}

export function ToggleMute() {
  return window['go']['main']['App']['ToggleMute']();
}

export function VolumeDown() {
  return window['go']['main']['App']['VolumeDown']();
}

export function VolumeUp() {
  return window['go']['main']['App']['VolumeUp']();
}
