// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {media} from '../models';
import {shortcuts} from '../models';

export function GetMedia():Promise<media.MediaInfo>;

export function GetShortcuts():Promise<Array<shortcuts.Shortcut>>;

export function Next():Promise<void>;

export function OpenFocusSettings():Promise<void>;

export function OpenNotifications():Promise<void>;

export function OpenShortcut(arg1:number):Promise<void>;

export function PlayPause():Promise<void>;

export function Previous():Promise<void>;

export function ToggleMute():Promise<void>;

export function VolumeDown():Promise<void>;

export function VolumeUp():Promise<void>;
